"""Golden vectors generated by running the REAL macula_blake3_nif (the
Rust-NIF-backed BLAKE3, not its pure-Erlang fallback -- see module doc)
directly against the actual macula checkout:

    #!/usr/bin/env escript
    %% -*- erlang -*-
    main(_) ->
        code:add_path("<macula checkout>/_build/default/lib/macula/ebin"),
        _ = code:ensure_loaded(macula_crypto_nif),
        true = macula_blake3_nif:is_nif_loaded(),
        io:format("~s~n", [binary:encode_hex(macula_blake3_nif:hash(<<"macula">>))]),
        io:format("~s~n", [binary:encode_hex(macula_blake3_nif:hash(<<>>))]),
        io:format("~s~n", [binary:encode_hex(macula_blake3_nif:hash(binary:copy(<<0>>, 1000)))]).
"""

from macula import blake3_hash

GOLDEN_VECTORS = {
    b"macula": "cff544e74792764abe735af6a4f6422f138d659145de6f9a181d30929df40ab1",
    b"": "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
    bytes(1000): "e8d303b248309a611deca3391a7b07adfca71e98d91e216bd23dab50a4765ee3",
}


def test_hash_bytes_matches_the_real_nif_backed_blake3_byte_for_byte():
    for data, want_hex in GOLDEN_VECTORS.items():
        assert blake3_hash.hash_bytes(data).hex() == want_hex


def test_hash_hex_matches_hash_bytes():
    for data in GOLDEN_VECTORS:
        assert blake3_hash.hash_hex(data) == blake3_hash.hash_bytes(data).hex()


def test_digest_is_32_bytes():
    assert len(blake3_hash.hash_bytes(b"anything")) == blake3_hash.DIGEST_SIZE == 32


def test_verify_accepts_a_correct_hash_and_rejects_a_wrong_one():
    data = b"hello macula"
    correct = blake3_hash.hash_bytes(data)
    wrong = bytes(32)
    assert blake3_hash.verify(data, correct)
    assert not blake3_hash.verify(data, wrong)


def test_different_inputs_produce_different_hashes():
    assert blake3_hash.hash_bytes(b"a") != blake3_hash.hash_bytes(b"b")


def test_hash_is_deterministic():
    data = b"deterministic check"
    assert blake3_hash.hash_bytes(data) == blake3_hash.hash_bytes(data)
